name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Release Notary
        uses: docker://outillage/release-notary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
